theme: jekyll-theme-minimal
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: My digital garden
include: ['_pages']
exclude: []

collections:
  pages:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*.md"
    values:
      layout: "test"
  - scope:
      path: "_pages/*.md"
    values:
      layout: "default"