source "https://rubygems.org"
# gem "jekyll"
gem "jekyll", "~> 3.9"
gem "kramdown-parser-gfm", "~> 1.1.0"
gem "sprockets", "~> 3.7"
gem "minima"
group :jekyll_plugins do
  gem "jekyll-feed"
end
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo"
  gem "tzinfo-data"
end
gem "webrick"
gem 'github-pages', group: :jekyll_plugins